### PR TITLE
Update projects.yml

### PR DESCRIPTION
**Pull request by kendfrey**
Added rubiks-cube-group at the encouragement of @kbuzzard.

### CODE REVIEW

**Comment by robertylewis** [comment]
Thanks!

I strongly recommend installing the CI scripts at https://leanprover-community.github.io/ci.html .

**Comment by robertylewis** [comment]
@kendfrey Note that your project doesn't build right now, so you'll have an `x` on the project page until it's fixed.

**Comment by kendfrey** [comment]
@robertylewis I've fixed the build. Do I need to do anything else to get the project page to update, or will it do that on its own?

**Comment by robertylewis** [comment]
It will do that on its own, normally in the middle of the night UTC. But I'll trigger it now.

If you put the GitHub Actions scripts in your repo (it's just copying two files), you'll be notified if and when the build breaks in the future.

**Pull request merged**
